### PR TITLE
added cakeevent overview in group-screen

### PR DESCRIPTION
**Pull request by Jacky-Ickx**
- also made sure that cakeevents always contain a name
- fixed a small logic error
- made mostRecentCake work

### CODE REVIEW

**Review by grossamos — CHANGES_REQUESTED** [review]
still some styling issues with smaller displays:
image
 I'm guessing the width should be simmilar here.

Appart from that, functionality and code looks great

**Comment by grossamos** [comment]
looks like a bigger issue with the `app-chip` component I wrote, yaayyy

will look at this in detail tomorrow (need sleep)

**Comment by Jacky-Ickx** [comment]
yea thought it looked kinda weird as well but couldn't quite put my finger on what was wrong.

have fun styling ^^

**Comment by Jacky-Ickx** [comment]
closes #20

**Pull request merged**
